.TH mumble\-overlay 1 "2015 December 27"
.SH NAME
mumble\-overlay \- load OpenGL overlay for Mumble.
.SH SYNOPSIS
.B mumble\-overlay
.RI "executable"
.SH DESCRIPTION
This wrapper will load the OpenGL overlay for Mumble into the application
of your choice. This allows you to easily see who is talking even in
fullscreen games and applications.
.PP
Nothing will be shown unless you have Mumble running and it is
currently connected to a server.
.SH ENVIRONMENT VARIABLES
.TP
.B MUMBLE_OVERLAY_DEBUG
If this environment variable is set, extended debugging will be output to
standard output. Only useful for debugging.
.SH EXAMPLE
To run glxgears with the mumble\-overlay active:
.IP
mumble\-overlay glxgears
.SH NOTES
This will only work with OpenGL drivers which support the full
OpenGL and GLX specifications.
.SH SEE ALSO
.BR mumble (1),
.BR murmurd (1).
.SH AUTHORS
mumble and murmurd were written by The Mumble Developers.
