.TH MUMBLE 1 "2008 Januar 07"
.SH NAME
mumble \- a low\-latency, high quality voice chat program for gaming.
.SH SYNOPSIS
.B mumble
.SH DESCRIPTION
Mumble is a low\-latency, high quality voice chat utility for
gaming that runs under X11.
.SH SEE ALSO
.BR mumble\-overlay (1),
.BR murmurd (1).
.br
.SH AUTHOR
mumble and murmurd was written by Thorvald Natvig
<slicer@users.sourceforge.net>.
