.TH murmur\-user\-wrapper 1 "2008 May 09"
.SH NAME
murmur\-user\-wrapper \- User wrapper for murmurd.
.SH SYNOPSIS
.B murmur\-user\-wrapper
.RI [ options ]
.SH DESCRIPTION
Murmur is the server component of Mumble, a low\-latency, high quality VoIP
application. Murmur\-wrapper is a wrapper script to make it easier for normal
users to set up their own, private murmur server.
.SH OPTIONS
.TP
.BI \-d \ "directory"
Set directory to use. By default, the wrapper script uses $HOME/murmur
.TP
.B \-s
Check if murmur process is running.
.TP
.B \-k
Terminate running murmur process.
.TP
.B \-i
Initialize only, do not start the server.
.TP
.BI \-p \ "password"
Specify password for the SuperUser account and exit. SuperUser is the
mumble equivalent of root, a special user which bypasses all access
restrictions.
.SH NOTES
To create your own private server, you first want to run
.IP
murmur\-user\-wrapper \-i
.LP
Then edit ~/murmur/murmur.ini to set the various configuration settings. The
most important is probably the port; unless you're the only murmur process
running on this server, you'll need to change it.

When you're happy with your settings, you need to set the password for
SuperUser, which is your administrator account.
.IP
murmur\-user\-wrapper \-p 
.I "<password>"
.LP

Once this is done, simply run
.IP
murmur\-user\-wrapper
.LP
to start the server.
.SH SEE ALSO
.BR murmurd (1).
.br
.SH AUTHOR
mumble and murmurd was written by Thorvald Natvig
<slicer@users.sourceforge.net>.
