.TH murmurd 1 "2014 October 23"
.SH NAME
murmurd \- VoIP server.
.SH SYNOPSIS
.B murmurd
.RI [ options ]
.SH DESCRIPTION
Murmur is the server component of Mumble, a low\-latency, high quality VoIP
application.
.SH OPTIONS
.TP
.B \-h, \-help, \-\-help
Show a summary of the options.
.TP
.BI \-ini \ "inifile"
Specify which inifile to use. Without this option, murmur will search for
a murmur.ini file and will fall back to builtin defaults if one isn't found.
.TP
.B \-fg
Run in the foreground (do not fork).
.br
This is very useful for debugging.
.TP
.B \-v
Verbose mode, slightly more information is logged.
.TP
.BI \-supw \ "password" \ [ "serverid" ]
This will forcefully set the SuperUser password for a server. SuperUser is
a special account (similar to
.RI root
) which bypasses all access controls. This command may be used while the
server is running.
.TP
.BI \-readsupw \ [srv]
Reads password for server srv from standard input.
.TP
.B \-limits
Tests and shows how many file descriptors and threads can be created. The purpose of this option is to test how many clients Murmur can handle. Murmur will exit after this test.
.TP
.B \-wipessl
Remove SSL certificates from database.
.TP
.B \-wipelogs
Remove all log entries from database.
.TP
.B \-version, \-\-version
Show version information.
.SH SEE ALSO
.BR mumble (1),
.BR murmur\-wrapper (1).
.br
.SH AUTHORS
mumble and murmurd were written by the Mumble team.
