#!/bin/bash

INSTALL_PKG=$1
INSTALL_DEST=$2
INSTALL_VOL=$3
INSTALL_ROOT=$4

# Change owner/group of app bundle
chown -R root:admin ${INSTALL_DEST}/Applications/Mumble.app/
chown -R root:admin ${INSTALL_DEST}/Applications/Mumble11x.app/
