# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

image: Visual Studio 2022

clone_depth: 1
skip_branch_with_pr: true

environment:
  global:
    MUMBLE_BUILD_NUMBER_TOKEN:
      secure: scRizsdwbTWjY7M9RHPT9EXDBxtWvXTsyVq1xXTWF1A=
    MUMBLE_ENVIRONMENT_SOURCE: 'https://github.com/mumble-voip/vcpkg/releases/download/2025-02/'
    MUMBLE_ENVIRONMENT_STORE: 'C:/MumbleBuild'
    MUMBLE_ENVIRONMENT_PATH: '%MUMBLE_ENVIRONMENT_STORE%/%MUMBLE_ENVIRONMENT_VERSION%'
    MUMBLE_ENVIRONMENT_TOOLCHAIN: '%MUMBLE_ENVIRONMENT_PATH%/scripts/buildsystems/vcpkg.cmake'
    MUMBLE_SOURCE_COMMIT: '%APPVEYOR_REPO_COMMIT%'
    MUMBLE_SOURCE_REPOSITORY: '%APPVEYOR_BUILD_FOLDER%'
    MUMBLE_BUILD_DIRECTORY: '%MUMBLE_SOURCE_REPOSITORY%/build'
    MUMBLE_USE_ELEVATION: 'ON'
    MUMBLE_SKIP_MSI_REBUILD: 'OFF'
    SIGNPATH_PROJECT_SLUG: 'mumble'
    SIGNPATH_ARTIFACT_CONFIGURATION: 'release-signing'
    SIGNPATH_SIGNING_POLICY_STAGE_1: 'sign-msi'
    SIGNPATH_SIGNING_POLICY_STAGE_2: 'sign-engine'
    SIGNPATH_SIGNING_POLICY_STAGE_3: 'sign-bundle'
    SIGNPATH_ORGANIZATION_ID: '79916aba-7a9f-448d-91c6-fb83593b59d3'
    SIGNPATH_API_TOKEN:
      secure: WKbGSfFSHTtODf6eHRSHPAobctJli48O/VoMpCYTuIlITl2piOpCH6igCRDX4EuJTzgDX45H34tVfPuNzSMdLA==


  matrix:
    - MUMBLE_ENVIRONMENT_TRIPLET: 'x64-windows-static-md'
      MUMBLE_ENVIRONMENT_VERSION: 'mumble_env.x64-windows-static-md.2025-02-27.fa0adb3ba5'

install:
  - ps: .ci/install-environment_windows.ps1
  - ps: Install-Module -Name SignPath

before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && git submodule update --init --recursive

build_script:
  - cmd: .ci/build_windows.bat

after_build:
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && 7z a unsigned_msi.zip installer/client/*.msi installer/server/*.msi
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && del installer/client/*.msi && del installer/server/*.msi && del installer/client/*client*.exe && del installer/server/*server*.exe
  - ps: |
      Submit-SigningRequest `
        -InputArtifactPath "$env:MUMBLE_BUILD_DIRECTORY/unsigned_msi.zip" `
        -ProjectSlug $env:SIGNPATH_PROJECT_SLUG -ArtifactConfigurationSlug $env:SIGNPATH_ARTIFACT_CONFIGURATION -SigningPolicySlug $env:SIGNPATH_SIGNING_POLICY_STAGE_1 `
        -WaitForCompletion -OutputArtifactPath "$env:MUMBLE_BUILD_DIRECTORY/signed_msi.zip" `
        -OrganizationId $env:SIGNPATH_ORGANIZATION_ID -ApiToken $env:SIGNPATH_API_TOKEN
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && 7z x "signed_msi.zip" -o"."
  - cmd: set MUMBLE_SKIP_MSI_REBUILD=ON && call .ci/build_windows.bat
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && C:/WixSharp/Wix_bin/insignia.exe -ib installer/client/*client*.exe -o installer/client/engine.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && C:/WixSharp/Wix_bin/insignia.exe -ib installer/server/*server*.exe -o installer/server/engine.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && 7z a unsigned_engine.zip installer/client/engine.exe installer/server/engine.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && del installer/client/engine.exe && del installer/server/engine.exe
  - ps: |
      Submit-SigningRequest `
        -InputArtifactPath "$env:MUMBLE_BUILD_DIRECTORY/unsiged_engine.zip" `
        -ProjectSlug $env:SIGNPATH_PROJECT_SLUG -ArtifactConfigurationSlug $env:SIGNPATH_ARTIFACT_CONFIGURATION -SigningPolicySlug $env:SIGNPATH_SIGNING_POLICY_STAGE_2 `
        -WaitForCompletion -OutputArtifactPath "$env:MUMBLE_BUILD_DIRECTORY/signed_engine.zip" `
        -OrganizationId $env:SIGNPATH_ORGANIZATION_ID -ApiToken $env:SIGNPATH_API_TOKEN
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && 7z x "signed_engine.zip" -o"."
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && C:/WixSharp/Wix_bin/insignia.exe -ab installer/client/engine.exe installer/client/*client*.exe -o installer/client/*client*.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && C:/WixSharp/Wix_bin/insignia.exe -ab installer/server/engine.exe installer/server/*server*.exe -o installer/server/*client*.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && del installer/client/engine.exe && del installer/server/engine.exe
  - cmd: cd "%MUMBLE_BUILD_DIRECTORY%" && 7z a binaries.zip *.exe *.dll *.pdb plugins/*.dll plugins/*.pdb installer/client/*.exe installer/server/*.exe installer/client/*.msi installer/server/*.msi

artifacts:
  - path: 'build/binaries.zip'
    name: 'Binaries'

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/%SIGNPATH_ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_STAGE_3%&ArtifactConfigurationSlug=%SIGNPATH_ARTIFACT_CONFIGURATION%
    authorization: '%SIGNPATH_API_TOKEN%'
