TEMPLATE	=app
CONFIG  += qt thread warn_on network release console
QT           += network
TARGET = mumble
DBFILE  = mumble.db
LANGUAGE	= C++
RC_FILE = mumble.rc
FORMS = 
HEADERS = MainWindow.h Connection.h ServerHandler.h
SOURCES = main.cpp MainWindow.cpp Message.cpp Connection.cpp ServerHandler.h
INCLUDEPATH += include /dx90sdk/include
LIBS +=  -Llib -llibspeex -L\\dx90sdk\\lib -ldsound -ldxguid -ldinput8 -lwinmm -lws2_32
