TEMPLATE	=app
CONFIG  += qt thread warn_on network console debug release
CONFIG	-= gui
QT           += network
TARGET = murmur
DBFILE  = murmur.db
LANGUAGE	= C++
RC_FILE = mumble.rc
FORMS = 
HEADERS = Server.h Connection.h Player.h
SOURCES = murmur.cpp  Message.cpp Connection.cpp Server.cpp Player.cpp
