/*
 * This file was auto-generated by scripts/mklic.pl
 * DO NOT EDIT IT MANUALLY
 */
#include <QtGlobal>

static const char *licenseMumble = 
	"Copyright (C) 2005-2011, Thorvald Natvig <thorvald@natvig.com>\n"
	"Copyright (C) 2007, Stefan Gehn <mETz AT gehn DOT net>\n"
	"Copyright (C) 2007, Sebastian Schlingmann <mit_service@users.sourceforge.net>\n"
	"Copyright (C) 2008-2011, Mikkel Krautz <mikkel@krautz.dk>\n"
	"Copyright (C) 2008, Andreas Messer <andi@bupfen.de>\n"
	"Copyright (C) 2007, Trenton Schulz\n"
	"Copyright (C) 2008-2011, Stefan Hacker <dd0t@users.sourceforge.net>\n"
	"Copyright (C) 2008-2011, Snares <snares@users.sourceforge.net>\n"
	"Copyright (C) 2009-2011, Benjamin Jemlich <pcgod@users.sourceforge.net>\n"
	"\n"
	"All rights reserved.\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright notice,\n"
	"  this list of conditions and the following disclaimer.\n"
	"- Redistributions in binary form must reproduce the above copyright notice,\n"
	"  this list of conditions and the following disclaimer in the documentation\n"
	"  and/or other materials provided with the distribution.\n"
	"- Neither the name of the Mumble Developers nor the names of its\n"
	"  contributors may be used to endorse or promote products derived from this\n"
	"  software without specific prior written permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"`AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR\n"
	"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
	"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
	"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
	"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
	"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
	"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


static const char *licenseCELT = 
	"Copyright 2001-2009 Jean-Marc Valin, Timothy B. Terriberry,\n"
	"                    CSIRO, and other contributors\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR\n"
	"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
	"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
	"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
	"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
	"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
	"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


static const char *licenseOpus = 
	"Copyright 2001-2011 Xiph.Org, Skype Limited, Octasic,\n"
	"                    Jean-Marc Valin, Timothy B. Terriberry,\n"
	"                    CSIRO, Gregory Maxwell, Mark Borgerding,\n"
	"                    Erik de Castro Lopo\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"- Neither the name of Internet Society, IETF or IETF Trust, nor the \n"
	"names of specific contributors, may be used to endorse or promote\n"
	"products derived from this software without specific prior written\n"
	"permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER\n"
	"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
	"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
	"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
	"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
	"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
	"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
	"\n"
	"Opus is subject to the royalty-free patent licenses which are\n"
	"specified at:\n"
	"\n"
	"Xiph.Org Foundation:\n"
	"https://datatracker.ietf.org/ipr/1524/\n"
	"\n"
	"Skype Limited:\n"
	"https://datatracker.ietf.org/ipr/1602/\n"
	"\n"
	"Broadcom Corporation:\n"
	"https://datatracker.ietf.org/ipr/1526/";


static const char *licenseSPEEX = 
	"Copyright 2002-2008 	Xiph.org Foundation\n"
	"Copyright 2002-2008 	Jean-Marc Valin\n"
	"Copyright 2005-2007	Analog Devices Inc.\n"
	"Copyright 2005-2008	Commonwealth Scientific and Industrial Research \n"
	"                        Organisation (CSIRO)\n"
	"Copyright 1993, 2002, 2006 David Rowe\n"
	"Copyright 2003 		EpicGames\n"
	"Copyright 1992-1994	Jutta Degener, Carsten Bormann\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"- Neither the name of the Xiph.org Foundation nor the names of its\n"
	"contributors may be used to endorse or promote products derived from\n"
	"this software without specific prior written permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR\n"
	"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
	"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
	"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
	"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
	"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
	"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


static const char *licenseOpenSSL = 
	"====================================================================\n"
	"Copyright (c) 1998-2011 The OpenSSL Project.  All rights reserved.\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"1. Redistributions of source code must retain the above copyright\n"
	"   notice, this list of conditions and the following disclaimer. \n"
	"\n"
	"2. Redistributions in binary form must reproduce the above copyright\n"
	"   notice, this list of conditions and the following disclaimer in\n"
	"   the documentation and/or other materials provided with the\n"
	"   distribution.\n"
	"\n"
	"3. All advertising materials mentioning features or use of this\n"
	"   software must display the following acknowledgment:\n"
	"   \"This product includes software developed by the OpenSSL Project\n"
	"   for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n"
	"\n"
	"4. The names \"OpenSSL Toolkit\" and \"OpenSSL Project\" must not be used to\n"
	"   endorse or promote products derived from this software without\n"
	"   prior written permission. For written permission, please contact\n"
	"   openssl-core@openssl.org.\n"
	"\n"
	"5. Products derived from this software may not be called \"OpenSSL\"\n"
	"   nor may \"OpenSSL\" appear in their names without prior written\n"
	"   permission of the OpenSSL Project.\n"
	"\n"
	"6. Redistributions of any form whatsoever must retain the following\n"
	"   acknowledgment:\n"
	"   \"This product includes software developed by the OpenSSL Project\n"
	"   for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n"
	"EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
	"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n"
	"PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n"
	"ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
	"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n"
	"NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
	"LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
	"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n"
	"STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n"
	"ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n"
	"OF THE POSSIBILITY OF SUCH DAMAGE.\n"
	"====================================================================\n"
	"\n"
	"This product includes cryptographic software written by Eric Young\n"
	"(eay@cryptsoft.com).  This product includes software written by Tim\n"
	"Hudson (tjh@cryptsoft.com).";


static const char *licenseLibsndfile = 
	"Copyright (C) 1999-2011 Erik de Castro Lopo <erikd@mega-nerd.com>\n"
	"\n"
	"This program is free software; you can redistribute it and/or modify\n"
	"it under the terms of the GNU Lesser General Public License as published by\n"
	"the Free Software Foundation; either version 2.1 of the License, or\n"
	"(at your option) any later version.\n"
	"\n"
	"This program is distributed in the hope that it will be useful,\n"
	"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
	"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
	"GNU Lesser General Public License for more details.\n"
	"\n"
	"You should have received a copy of the GNU Lesser General Public License\n"
	"along with this program; if not, write to the Free Software\n"
	"Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.";


static const char *licenseOgg = 
	"Copyright (c) 2002, Xiph.org Foundation\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"- Neither the name of the Xiph.org Foundation nor the names of its\n"
	"contributors may be used to endorse or promote products derived from\n"
	"this software without specific prior written permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
	"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
	"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
	"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
	"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
	"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
	"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
	"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


static const char *licenseVorbis = 
	"Copyright (c) 2002-2008 Xiph.org Foundation\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"- Neither the name of the Xiph.org Foundation nor the names of its\n"
	"contributors may be used to endorse or promote products derived from\n"
	"this software without specific prior written permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
	"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
	"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
	"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
	"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
	"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
	"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
	"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


static const char *licenseFLAC = 
	"Copyright (C) 2000,2001,2002,2003,2004,2005,2006,2007  Josh Coalson\n"
	"\n"
	"Redistribution and use in source and binary forms, with or without\n"
	"modification, are permitted provided that the following conditions\n"
	"are met:\n"
	"\n"
	"- Redistributions of source code must retain the above copyright\n"
	"notice, this list of conditions and the following disclaimer.\n"
	"\n"
	"- Redistributions in binary form must reproduce the above copyright\n"
	"notice, this list of conditions and the following disclaimer in the\n"
	"documentation and/or other materials provided with the distribution.\n"
	"\n"
	"- Neither the name of the Xiph.org Foundation nor the names of its\n"
	"contributors may be used to endorse or promote products derived from\n"
	"this software without specific prior written permission.\n"
	"\n"
	"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
	"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
	"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
	"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR\n"
	"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
	"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
	"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
	"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
	"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
	"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";


#ifdef Q_OS_MAC
static const char *licenseMachOverride = 
	"Copyright (c) 2003-2009 Jonathan 'Wolf' Rentzsch <http://rentzsch.com>\n"
	"\n"
	"Permission is hereby granted, free of charge, to any person obtaining\n"
	"a copy of this software and associated documentation files (the \"Software\"),\n"
	"to deal in the Software without restriction, including without limitation\n"
	"the rights to use, copy, modify, merge, publish, distribute, sublicense,\n"
	"and/or sell copies of the Software, and to permit persons to whom the\n"
	"Software is furnished to do so, subject to the following conditions:\n"
	"\n"
	"The above copyright notice and this permission notice shall be\n"
	"included in all copies or substantial portions of the Software.\n"
	"\n"
	"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS\n"
	"OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
	"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\n"
	"THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
	"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
	"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
	"THE SOFTWARE.";


#endif
#ifdef USING_BUNDLED_QT_TRANSLATIONS
static const char *licenseQtTranslations = 
	"Mumble uses Qt translations created by the VirtualBox community\n"
	"under the MIT license. Files and copyright were obtained from:\n"
	"https://www.virtualbox.org/ticket/2018\n"
	"\n"
	"Turkish Qt translation (serdar, BouRock):\n"
	"  Copyright (c) 2007-2009 Serdar Soytetir\n"
	"  Copyright (c) 2012 Burak Yavuz\n"
	"Italian Qt translation (smart2128):\n"
	"  Copyright (c) 2009-2012 Vincenzo Reale\n"
	"Dutch Qt translation (geertseb, lxndr, nippur):\n"
	"  Copyright (c) 2009-2011 Ebel Geertsema\n"
	"  Copyright (c) 2007 Alexander L. de Goeij\n"
	"  Copyright (c) 2012 Richard E van der Luit\n"
	"\n"
	"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
	"of this software and associated documentation files (the \"Software\"), to deal\n"
	"in the Software without restriction, including without limitation the rights\n"
	"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
	"copies of the Software, and to permit persons to whom the Software is furnished\n"
	"to do so, subject to the following conditions:\n"
	"\n"
	"The above copyright notice and this permission notice shall be included in all\n"
	"copies or substantial portions of the Software.\n"
	"\n"
	"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
	"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
	"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
	"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
	"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
	"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
	"SOFTWARE.";


#endif
static const char *licenses3rdParty[] = {
	licenseCELT, 
	licenseOpus, 
	licenseSPEEX, 
	licenseOpenSSL, 
	licenseLibsndfile, 
	licenseOgg, 
	licenseVorbis, 
	licenseFLAC, 
#ifdef Q_OS_MAC
	licenseMachOverride, 
#endif
#ifdef USING_BUNDLED_QT_TRANSLATIONS
	licenseQtTranslations, 
#endif
	0
};


static const char *licenses3rdPartyNames[] = {
	"Speex",
	"Opus",
	"CELT",
	"OpenSSL",
	"libsndfile",
	"libogg",
	"libvorbis",
	"libFLAC",
#ifdef Q_OS_MAC
	"mach_override",
#endif
#ifdef USING_BUNDLED_QT_TRANSLATIONS
	"Additional Qt translations",
#endif
	0
};


static const char *licenses3rdPartyURLs[] = {
	"http://www.speex.org/",
	"http://www.opus-codec.org/",
	"http://www.celt-codec.org/",
	"http://www.openssl.org/",
	"http://www.mega-nerd.com/libsndfile/",
	"http://www.xiph.org/",
	"http://www.xiph.org/",
	"http://flac.sourceforge.net/",
#ifdef Q_OS_MAC
	"https://github.com/rentzsch/mach_star",
#endif
#ifdef USING_BUNDLED_QT_TRANSLATIONS
	"https://www.virtualbox.org/ticket/2018",
#endif
	0
};


