// Copyright 2005-2017 The Mumble Developers. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file at the root of the
// Mumble source tree or at <https://www.mumble.info/LICENSE>.

// This table translates Windows virtual keycodes
// to user-readable strings.

static const char *vk_translation_tbl[] = {
	NULL,               // 0x00
	"LBUTTON",          // 0x01
	"RBUTTON",          // 0x02
	"CANCEL",           // 0x03
	"MBUTTON",          // 0x04
	"XBUTTON1",         // 0x05
	"XBUTTON2",         // 0x06
	NULL,               // 0x07
	"Backspace",        // 0x08
	"Tab",              // 0x09
	NULL,               // 0x0a
	NULL,               // 0x0b
	"Clear",            // 0x0c
	"Return",           // 0x0d
	NULL,               // 0x0e
	NULL,               // 0x0f
	"Shift",            // 0x10
	"Ctrl",             // 0x11
	"Alt",              // 0x12
	"Pause",            // 0x13
	"Caps Lock",        // 0x14
	"IME Kana/Hangul",  // 0x15
	NULL,               // 0x16
	"Junja",            // 0x17
	"Final",            // 0x18
	"Hanja/Kanji",      // 0x19
	NULL,               // 0x1a
	"Esc",              // 0x1b
	"Convert",          // 0x1c
	"Non-convert",      // 0x1d
	"Accept",           // 0x1e
	"ModeChange",       // 0x1f
	"Space",            // 0x20
	"PageUp",           // 0x21
	"PageDown",         // 0x22
	"End",              // 0x23
	"Home",             // 0x24
	"LeftArrow",        // 0x25
	"UpArrow",          // 0x26
	"RightArrow",       // 0x27
	"DownArrow",        // 0x28
	"Select",           // 0x29
	"Print",            // 0x2a
	"Execute",          // 0x2b
	"PrintScreen",      // 0x2c
	"Insert",           // 0x2d
	"Delete",           // 0x2e
	"Help",             // 0x2f
	"0",                // 0x30
	"1",                // 0x31
	"2",                // 0x32
	"3",                // 0x33
	"4",                // 0x34
	"5",                // 0x35
	"6",                // 0x36
	"7",                // 0x37
	"8",                // 0x38
	"9",                // 0x39
	NULL,               // 0x3a
	NULL,               // 0x3b
	NULL,               // 0x3c
	NULL,               // 0x3d
	NULL,               // 0x3e
	NULL,               // 0x3f
	NULL,               // 0x40
	"A",                // 0x41
	"B",                // 0x42
	"C",                // 0x43
	"D",                // 0x44
	"E",                // 0x45
	"F",                // 0x46
	"G",                // 0x47
	"H",                // 0x48
	"I",                // 0x49
	"J",                // 0x4a
	"K",                // 0x4b
	"L",                // 0x4c
	"M",                // 0x4d
	"N",                // 0x4e
	"O",                // 0x4f
	"P",                // 0x50
	"Q",                // 0x51
	"R",                // 0x52
	"S",                // 0x53
	"T",                // 0x54
	"U",                // 0x55
	"V",                // 0x56
	"W",                // 0x57
	"X",                // 0x58
	"Y",                // 0x59
	"Z",                // 0x5a
	"LeftWindows",      // 0x5b
	"RightWindows",     // 0x5c
	"Apps",             // 0x5d
	NULL,               // 0x5e
	"Sleep",            // 0x5f
	"Numpad0",          // 0x60
	"Numpad1",          // 0x61
	"Numpad2",          // 0x62
	"Numpad3",          // 0x63
	"Numpad4",          // 0x64
	"Numpad5",          // 0x65
	"Numpad6",          // 0x66
	"Numpad7",          // 0x67
	"Numpad8",          // 0x68
	"Numpad9",          // 0x69
	"Multiply",         // 0x6a
	"Add",              // 0x6b
	"Separator",        // 0x6c
	"Subtract",         // 0x6d
	"Decimal",          // 0x6e
	"Divide",           // 0x6f
	"F1",               // 0x70
	"F2",               // 0x71
	"F3",               // 0x72
	"F4",               // 0x73
	"F5",               // 0x74
	"F6",               // 0x75
	"F7",               // 0x76
	"F8",               // 0x77
	"F9",               // 0x78
	"F10",              // 0x79
	"F11",              // 0x7a
	"F12",              // 0x7b
	"F13",              // 0x7c
	"F14",              // 0x7d
	"F15",              // 0x7e
	"F16",              // 0x7f
	"F17",              // 0x80
	"F18",              // 0x81
	"F19",              // 0x82
	"F20",              // 0x83
	"F21",              // 0x84
	"F22",              // 0x85
	"F23",              // 0x86
	"F24",              // 0x87
	NULL,               // 0x88
	NULL,               // 0x89
	NULL,               // 0x8a
	NULL,               // 0x8b
	NULL,               // 0x8c
	NULL,               // 0x8d
	NULL,               // 0x8e
	NULL,               // 0x8f
	"NumLock",          // 0x90
	"ScrollLock",       // 0x91
	"OEM92",            // 0x92
	"OEM93",            // 0x93
	"OEM94",            // 0x94
	"OEM95",            // 0x95
	"OEM96",            // 0x96
	NULL,               // 0x97
	NULL,               // 0x98
	NULL,               // 0x99
	NULL,               // 0x9a
	NULL,               // 0x9b
	NULL,               // 0x9c
	NULL,               // 0x9d
	NULL,               // 0x9e
	NULL,               // 0x9f
	"LeftShift",        // 0xa0
	"RightShift",       // 0xa1
	"LeftControl",      // 0xa2
	"RightControl",     // 0xa3
	"LeftMenu",         // 0xa4
	"RightMenu",        // 0xa5
	"BrowserBack",      // 0xa6
	"BrowserForward",   // 0xa7
	"BrowserRefresh",   // 0xa8
	"BrowserStop",      // 0xa9
	"BrowserSearch",    // 0xaa
	"BrowserFavorites", // 0xab
	"BrowserHome",      // 0xac
	"VolumeMute",       // 0xad
	"VolumeDown",       // 0xae
	"VolumeUp",         // 0xaf
	"MediaNextTrack",   // 0xb0
	"MediaPrevTrack",   // 0xb1
	"MediaStop",        // 0xb2
	"MediaPlayPause",   // 0xb3
	"Mail",             // 0xb4
	"SelectMedia",      // 0xb5
	"StartApp1",        // 0xb6
	"StartApp2",        // 0xb7
	NULL,               // 0xb8
	NULL,               // 0xb9
	"OEM1",             // 0xba
	"OEMPlus",          // 0xbb
	"OEMComma",         // 0xbc
	"OEMMinus",         // 0xbd
	"OEMPeriod",        // 0xbe
	"OEM2",             // 0xbf
	"OEM3",             // 0xc0
	NULL,               // 0xc1
	NULL,               // 0xc2
	NULL,               // 0xc3
	NULL,               // 0xc4
	NULL,               // 0xc5
	NULL,               // 0xc7
	NULL,               // 0xc8
	NULL,               // 0xc9
	NULL,               // 0xca
	NULL,               // 0xcb
	NULL,               // 0xcc
	NULL,               // 0xcd
	NULL,               // 0xce
	NULL,               // 0xcf
	NULL,               // 0xd0
	NULL,               // 0xd1
	NULL,               // 0xd2
	NULL,               // 0xd3
	NULL,               // 0xd4
	NULL,               // 0xd5
	NULL,               // 0xd6
	NULL,               // 0xd7
	NULL,               // 0xd8
	NULL,               // 0xd9
	NULL,               // 0xda
	"OEM4",             // 0xdb
	"OEM5",             // 0xdc
	"OEM6",             // 0xdd
	"OEM7",             // 0xde
	"OEM8",             // 0xdf
	NULL,               // 0xe0
	NULL,               // 0xe1
	"OEM102",           // 0xe2
	"OEME3",            // 0xe3
	"OEME4",            // 0xe4
	"IMEProcess",       // 0xe5
	"OEME6",            // 0xe6
	"VKPacket",         // 0xe7
	NULL,               // 0xe8
	"OEME9",            // 0xe9
	"OEMEA",            // 0xea
	"OEMEB",            // 0xeb
	"OEMEC",            // 0xec
	"OEMED",            // 0xed
	"OEMEE",            // 0xee
	"OEMEF",            // 0xef
	"OEMF0",            // 0xf0
	"OEMF1",            // 0xf1
	"OEMF2",            // 0xf2
	"OEMF3",            // 0xf3
	"OEMF4",            // 0xf4
	"OEMF5",            // 0xf5
	"Attn",             // 0xf6
	"CrSel",            // 0xf7
	"ExSel",            // 0xf8
	"EraseEOF",         // 0xf9
	"Play",             // 0xfa
	"Zoom",             // 0xfb
	"Noname",           // 0xfc
	"PA1",              // 0xfd
	"Clear"             // 0xfe
};

/// Perform a lookup into the vk_translation_tbl. This function
/// automatically returns NULL for out-of-range virtual keycodes.
static inline const char *vk_translation_tbl_lookup(unsigned int vktype) {
	if (vktype > 0xfe) {
		return NULL;
	}
	return vk_translation_tbl[vktype];
}
