# Copyright 2020-2023 The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

variables:
  MUMBLE_ENVIRONMENT_STORE: '$(Agent.ToolsDirectory)/MumbleBuild'
  MUMBLE_ENVIRONMENT_SOURCE: 'https://github.com/mumble-voip/vcpkg/releases/download/2025-07_qt5'
  MUMBLE_ENVIRONMENT_PATH: '$(MUMBLE_ENVIRONMENT_STORE)/$(MUMBLE_ENVIRONMENT_VERSION)'
  MUMBLE_ENVIRONMENT_TOOLCHAIN: '$(MUMBLE_ENVIRONMENT_PATH)/scripts/buildsystems/vcpkg.cmake'
  MUMBLE_SOURCE_COMMIT: '$(Build.SourceVersion)'
  MUMBLE_SOURCE_REPOSITORY: '$(Build.SourcesDirectory)'
  MUMBLE_BUILD_DIRECTORY: '$(Build.BinariesDirectory)'
  # On Azure we have a secret variable called BUILD_NUMBER_TOKEN that will be referenced in the following
  # YAML files. As it is set there though, we don't have to specify it here.

jobs:
  - job: Windows_x64
    workspace:
      clean: all
    timeoutInMinutes: 90
    pool:
      vmImage: 'windows-2022'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'mumble_env.x64-windows-static-md.2025-07-29.9578b83ca8'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x64-windows-static-md'
    steps:
    - template: steps_windows.yml
      parameters:
        arch: 'x64'

  - job: Linux
    workspace:
      clean: all
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - template: steps_linux.yml

  - job: macOS
    workspace:
      clean: all
    pool:
      vmImage: 'macOS-14'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'mumble_env.x64-osx.2025-08-05.9578b83ca8'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x64-osx'
    steps:
    - template: steps_macos.yml
      parameters:
        installEnvironment: true
