# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

parameters:
- name: installEnvironment
  type: boolean
  default: false

steps:
  - script: git submodule --quiet update --init --recursive
    displayName: 'Fetch submodules'
  - ${{if eq(parameters.installEnvironment, true)}}:
    - script: .ci/azure-pipelines/install-environment_macos.bash
      displayName: 'Install build environment'
  - script: .ci/azure-pipelines/build_macos.bash
    env:
      MUMBLE_BUILD_NUMBER_TOKEN: $(BUILD_NUMBER_TOKEN)
    displayName: 'Build'
  - script: 'cd $BUILD_BINARIESDIRECTORY; ctest --output-on-failure'
    displayName: 'Test'
  - script: .ci/azure-pipelines/release_macos.bash
    displayName: 'Release'
  - template: task-publish-artifacts.yml
    parameters:
      name: "macOS package" 
