#!/usr/bin/env python3

# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.


import argparse
import re
from datetime import datetime
import os

def comment_remover(text):
    def replacer(match):
        s = match.group(0)
        if s.startswith('/'):
            return ""
        else:
            return s
    pattern = re.compile(
        r'//.*?$|/\*.*?\*/|\'(?:\\.|[^\\\'])*\'|"(?:\\.|[^\\"])*"',
        re.DOTALL | re.MULTILINE
    )
    return re.sub(pattern, replacer, text)

def fix_lineEnding(text):
    # Convert from Windows to Unix
    text = text.replace("\r\n", "\n")
    # Convert from old Mac to Unix
    text = text.replace("\r", "\n")

    return text

def create_disclaimerComment():
    return "// This file was auto-generated by scripts/generateIceWrapper.py on " + datetime.now().strftime("%Y-%m-%d") + " -- DO NOT EDIT MANUALLY!\n"

def split_parameters(parameterList):
    # Split at top-level commas only, as template arguments may contain commas as well
    parameters = []
    depth = 0
    current = ""
    for c in parameterList:
        if c in "<(":
            depth += 1
        elif c in ">)":
            depth -= 1

        if c == "," and depth == 0:
            parameters.append(current.strip())
            current = ""
        else:
            current += c

    if current.strip():
        parameters.append(current.strip())

    return parameters

def parameter_name(parameter):
    return re.search(r"(\w+)$", parameter).group(1)

def generateFunction(className, functionName, parameters, callArgs):
    function = "void ::MumbleServer::" + className + "I::" + functionName + "Async(" + (", ".join(parameters)) + ") {\n"
    function += "\tconst ::MumbleServer::AMD_" + className + "_" + functionName + "Ptr amdCallback = std::make_shared< ::MumbleServer::AMD_" + className + "_" + functionName + "Ptr::element_type >(std::move(response), std::move(exception));\n"
    function += "\n"
    function += "\t// qWarning() << \"" + functionName + "\" << ::Meta::mp->qsIceSecretRead.isNull() << ::Meta::mp->qsIceSecretRead.isEmpty();\n"
    function += "#ifndef ACCESS_" + className + "_" + functionName + "_ALL\n"
    function += "#\tifdef ACCESS_" + className + "_" + functionName + "_READ\n"
    function += "\tif (!::Meta::mp->qsIceSecretRead.isNull()) {\n"
    function += "\t\tbool ok = !::Meta::mp->qsIceSecretRead.isEmpty();\n"
    function += "#\telse\n"
    function += "\tif (!::Meta::mp->qsIceSecretRead.isNull() || !::Meta::mp->qsIceSecretWrite.isNull()) {\n"
    function += "\t\tbool ok = !::Meta::mp->qsIceSecretWrite.isEmpty();\n"
    function += "#\tendif // ACCESS_" + className + "_" + functionName + "_READ\n"
    function += "\t\t::Ice::Context::const_iterator i = current.ctx.find(\"secret\");\n"
    function += "\t\tok = ok && (i != current.ctx.end());\n"
    function += "\t\tif (ok) {\n"
    function += "\t\t\tconst QString &secret = u8((*i).second);\n"
    function += "#\tifdef ACCESS_" + className + "_" + functionName + "_READ\n"
    function += "\t\t\tok = ((secret == ::Meta::mp->qsIceSecretRead) || (secret == ::Meta::mp->qsIceSecretWrite));\n"
    function += "#\telse\n"
    function += "\t\t\tok = (secret == ::Meta::mp->qsIceSecretWrite);\n"
    function += "#\tendif // ACCESS_" + className + "_" + functionName + "_READ\n"
    function += "\t\t}\n"
    function += "\n"
    function += "\t\tif (!ok) {\n"
    function += "\t\t\tamdCallback->ice_exception(InvalidSecretException());\n"
    function += "\t\t\treturn;\n"
    function += "\t\t}\n"
    function += "\t}\n"
    function += "#endif // ACCESS_" + className + "_" + functionName + "_ALL\n"
    function += "\n"
    function += "\tExecEvent *ie = new ExecEvent(std::bind(&impl_" + className + "_" + functionName + ", " + ", ".join(callArgs) + "));\n"
    function += "\tQCoreApplication::instance()->postEvent(mi, ie);\n"
    function += "}\n"

    return function


def main():
    parser = argparse.ArgumentParser(description="Generates the wrapper files needed for the ICE server-interface")
    parser.add_argument("-i", "--ice-file", help="Path to the ICE specification file (*.ice)", metavar="PATH")
    parser.add_argument("-g", "--generated-ice-header", help="Path to the header file that was generated by ICE", metavar="PATH")
    parser.add_argument("-o", "--out-file", help="Path to the file to write the generated output to. If omitted, the content will be written to std::out", metavar="PATH")
    parser.add_argument("--out-header", help="Path to the header file to write the generated declarations to. If omitted, the content will be written to std::out", metavar="PATH")
    parser.add_argument("-q", "--quiet", action="store_true", help="Don't display used file paths")

    args = parser.parse_args()

    scriptPath = os.path.realpath(__file__)
    rootDir = os.path.dirname(os.path.dirname(scriptPath))

    if args.ice_file is None:
        # Try to figure out the path to the ice-file (MumbleServer.ice)
        args.ice_file = os.path.join(rootDir, "src", "murmur", "MumbleServer.ice")
    if args.generated_ice_header is None:
        # Try to figure out path to the generated header file (in the build dir)
        args.generated_ice_header = os.path.join(rootDir, "build", "src", "murmur", "MumbleServer.h")

    if not args.quiet:
        print("Using ICE-file at                   \"%s\"" % args.ice_file)
        print("Using ICE-generated header file at  \"%s\"" % args.generated_ice_header)


    iceSpec = fix_lineEnding(open(args.ice_file, "r").read())
    generatedIceHeader = fix_lineEnding(open(args.generated_ice_header, "r").read())

    # remove comments from the iceSpec
    iceSpec = comment_remover(iceSpec)
    # Remove all tabs from iceSpec
    iceSpec = iceSpec.replace("\t", "")
    # Remove empty lines form iceSpec
    iceSpec = iceSpec.replace("\n\n", "\n")

    # Escape all special characters so that iceSpec can be used in a std::string ctor
    iceSpec = iceSpec.replace("\"", "\\\"") # quotes
    iceSpec = iceSpec.replace("\n", "\\n")  # newlines

    wrapperContent = create_disclaimerComment()
    wrapperContent += "\n#include <functional>\n#include <memory>\n\n"

    headerContent = create_disclaimerComment()
    headerContent += "\n#ifndef MUMBLE_MURMUR_MUMBLESERVERICEWRAPPER_H_\n"
    headerContent += "#define MUMBLE_MURMUR_MUMBLESERVERICEWRAPPER_H_\n"
    headerContent += "\n#include <memory>\n\n"
    headerContent += "namespace MumbleServer {\n\n"

    generatedIceHeader = comment_remover(generatedIceHeader)

    # The servant base classes of the C++11 mapping (Ice 3.7 generates code for the C++98 mapping as well, but
    # the Async signatures below only exist in the C++11 mapping)
    classPositions = [(m.start(), m.group(1)) for m in re.finditer(r"^class\s+(\w+)\s*:\s*public\s+virtual\s+(?:::)?Ice::Object\b", generatedIceHeader, re.MULTILINE)]

    # The AMD dispatch functions. These are matched on the entire header as they may span multiple lines and
    # may be preceded by macros or attributes (e.g. for deprecated functions).
    declarations = {}
    for match in re.finditer(r"virtual\s+void\s+(\w+)Async\(([^;]*?)\)\s*=\s*0\s*;", generatedIceHeader):
        functionName = match.group(1)
        parameters = split_parameters(" ".join(match.group(2).split()))

        className = None
        for position, name in classPositions:
            if position < match.start():
                className = name
        if className is None:
            raise RuntimeError("Unable to determine the class of function " + functionName)

        parameterNames = [parameter_name(p) for p in parameters]
        responseIndex = parameterNames.index("response")
        responseSignature = re.match(r"^(?:::)?std::function<(.*)>\s*response$", parameters[responseIndex]).group(1)
        inParameterNames = parameterNames[:responseIndex]
        currentName = parameterNames[-1]

        declarations.setdefault(className, []).append("\tvoid " + functionName + "Async(" + ", ".join(parameters) + ") override;\n")

        headerContent += "using AMD_" + className + "_" + functionName + "Ptr = std::shared_ptr< AMDCallback< " + responseSignature + " > >;\n"

        if functionName == "getSlice":
            # getSlice is handled separately
            # Omit the names of the unused parameters
            parameters = [p if parameter_name(p) == "response" else p[:-len(parameter_name(p))].strip() for p in parameters]
            wrapperContent += "void ::MumbleServer::MetaI::getSliceAsync(" + ", ".join(parameters) + ") {\n"
            wrapperContent += "\tresponse(std::string(\"" + iceSpec + "\"));\n"
            wrapperContent += "}\n\n"
            continue

        callArgs = ["amdCallback"]
        if className == "Server":
            callArgs.append("QString::fromStdString(" + currentName + ".id.name).toInt()")
        else:
            callArgs.append(currentName + ".adapter")
        callArgs += inParameterNames

        wrapperContent += generateFunction(className, functionName, parameters, callArgs) + "\n"

    for className in ["Server", "Meta"]:
        if not className in declarations:
            raise RuntimeError("No AMD functions found for class " + className)

        headerContent += "\nclass " + className + "I : public virtual " + className + " {\n"
        headerContent += "public:\n"
        headerContent += "".join(declarations[className])
        if className == "Server":
            headerContent += "\n\tvoid ice_ping(const ::Ice::Current &current) const override;\n"
        headerContent += "};\n"

    headerContent += "\n} // namespace MumbleServer\n"
    headerContent += "\n#endif\n"

    if args.out_file is None:
        # Write to std::out
        print(wrapperContent)
    else:
        # Write to file
        with open(args.out_file, "w") as outFile:
            outFile.write(wrapperContent)

    if args.out_header is None:
        print(headerContent)
    else:
        with open(args.out_header, "w") as outFile:
            outFile.write(headerContent)


main()
