#!/bin/bash

if [ -z "$1" -o "$1" = '--help' ]; then
	echo "USAGE: $0 <program> [args...]"
	exit 1
fi

for libpath in /usr/lib /usr/lib/mumble /usr/lib32 /usr/lib32/mumble /usr/lib64 /usr/lib64/mumble; do
  if [ -d "$libpath" ]; then
    if [ -f "$libpath/libmumble.so.1" ]; then
      case $(file -L "$libpath/libmumble.so.1") in
        *64-bit*) MUMBLE_OVERLAY_PATH_64="$libpath" ; echo set ;;
        *32-bit*) MUMBLE_OVERLAY_PATH_32="$libpath" ;;
      esac
    fi
  fi
done

if [ -f /etc/sysconfig/mumble ]; then
  . /etc/sysconfig/mumble
fi

binary="$1"
if [ "${binary/\/}" = "$binary" ]; then
  binary=$(which "$binary")
fi
if [ ! -x "$binary" ]; then
  echo "$1 not found" >&2
  exit 1
fi

is64=no
is32=no

case $(file -L "$binary") in
	*64-bit*)
		if [ -z "${MUMBLE_OVERLAY_PATH_64}" ]; then
			echo "64-bit libmumble.so.1 not found" >&2
			exit 1
		fi
		MUMBLE_PRELOAD="${MUMBLE_OVERLAY_PATH_64}/libmumble.so.1"
		;;
	*32-bit*)
		if [ -z "${MUMBLE_OVERLAY_PATH_32}" ]; then
			echo "32-bit libmumble.so.1 not found" >&2
			exit 1
		fi
		MUMBLE_PRELOAD="${MUMBLE_OVERLAY_PATH_32}/libmumble.so.1"
		;;
	*)
		if [ -n "${MUMBLE_OVERLAY_PATH_64}" ]; then
			MUMBLE_PRELOAD="${MUMBLE_OVERLAY_PATH_64}/libmumble.so.1"
		fi
		if [ -n "${MUMBLE_OVERLAY_PATH_32}" ]; then
			MUMBLE_PRELOAD="${MUMBLE_PRELOAD} ${MUMBLE_OVERLAY_PATH_32}/libmumble.so.1"
		fi
		if [ -z "${MUMBLE_PRELOAD}" ]; then
			echo "Neither 32-bit or 64-bit libmumble.so.1 found"
			exit 1
		fi
esac

LD_PRELOAD="${MUMBLE_PRELOAD} ${LD_PRELOAD}" "${@}"
