#! /bin/sh

if [ -d /usr/lib/mumble ]; then
  MUMBLE_OVERLAY_PATH=/usr/lib/mumble
else
  MUMBLE_OVERLAY_PATH=/usr/lib
fi

if [ -f /etc/sysconfig/mumble ]; then
  . /etc/sysconfig/mumble
fi

LD_PRELOAD="${MUMBLE_OVERLAY_PATH}/libmumble.so.1.1.3 ${LD_PRELOAD}" "${@}"
