// Copyright The Mumble Developers. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file at the root of the
// Mumble source tree or at <https://www.mumble.info/LICENSE>.

#ifndef MUMBLE_OVERLAY_AVAIL_MAC_H__
#define MUMBLE_OVERLAY_AVAIL_MAC_H__

// This file was auto-generated by 'avail_mac.pl'. Do not touch by hand.

#define AVAIL_ALL_GLSYM                                                                                                \
	(AVAIL(glActiveTexture) && AVAIL(glAttachShader) && AVAIL(glBindBuffer) && AVAIL(glBindFramebuffer)                \
	 && AVAIL(glBindTexture) && AVAIL(glBindVertexArray) && AVAIL(glBlendEquation) && AVAIL(glBlendEquationSeparate)   \
	 && AVAIL(glBlendFunc) && AVAIL(glBlendFuncSeparate) && AVAIL(glBufferData) && AVAIL(glBufferSubData)              \
	 && AVAIL(glColorMask) && AVAIL(glCompileShader) && AVAIL(glCreateProgram) && AVAIL(glCreateShader)                \
	 && AVAIL(glDeleteShader) && AVAIL(glDeleteTextures) && AVAIL(glDisable) && AVAIL(glDrawArrays) && AVAIL(glEnable) \
	 && AVAIL(glEnableVertexAttribArray) && AVAIL(glGenBuffers) && AVAIL(glGenTextures) && AVAIL(glGenVertexArrays)    \
	 && AVAIL(glGetBooleanv) && AVAIL(glGetError) && AVAIL(glGetIntegerv) && AVAIL(glGetProgramInfoLog)                \
	 && AVAIL(glGetProgramiv) && AVAIL(glGetShaderInfoLog) && AVAIL(glGetShaderiv) && AVAIL(glGetString)               \
	 && AVAIL(glGetTexParameterfv) && AVAIL(glGetUniformLocation) && AVAIL(glIsEnabled) && AVAIL(glIsTexture)          \
	 && AVAIL(glLinkProgram) && AVAIL(glPixelStorei) && AVAIL(glPolygonMode) && AVAIL(glShaderSource)                  \
	 && AVAIL(glTexImage2D) && AVAIL(glTexParameterfv) && AVAIL(glTexParameteri) && AVAIL(glTexSubImage2D)             \
	 && AVAIL(glUniform1i) && AVAIL(glUniformMatrix4fv) && AVAIL(glUseProgram) && AVAIL(glVertexAttribPointer)         \
	 && AVAIL(glViewport) && 1)

#endif
