# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

message(STATUS "Using Mumble's dependency provider")

include(FetchContent)
include(FindPackageHandleStandardArgs)

# Note: find_package (and FetchContent_MakeAvailable for that matter) have the package/dependency
# name as their first argument, which is why we can rely on that here as well.
macro(mumble_provide_dependency METHOD DEP_NAME)
	if (NOT "${METHOD}" STREQUAL "FIND_PACKAGE")
		message(FATAL_ERROR "mumble_provide_dependency called for unexpected method: ${METHOD}")
	endif()

	set(VARIABLES_TO_BE_CLEARED "VARIABLES_TO_BE_CLEARED")

	string(TOUPPER "${DEP_NAME}" DEP_NAME_UPPER)


	# Handle defaults while still respecting package-specific overwrites
	if (DEFINED MUMBLE_DEP_SKIP_FIND_PACKAGE AND NOT DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FIND_PACKAGE)
		set(MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FIND_PACKAGE ${MUMBLE_DEP_SKIP_FIND_PACKAGE})
		list(APPEND VARIABLES_TO_BE_CLEARED "MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FIND_PACKAGE")
	endif()
	if (DEFINED MUMBLE_DEP_SKIP_PKGCONF AND NOT DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_PKGCONFIG)
		set(MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_PKGCONFIG ${MUMBLE_DEP_SKIP_PKGCONF})
		list(APPEND VARIABLES_TO_BE_CLEARED "MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FIND_PACKAGE")
	endif()
	if (DEFINED MUMBLE_DEP_SKIP_FETCHCONTENT AND NOT DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FETCHCONTENT)
		set(MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FETCHCONTENT ${MUMBLE_DEP_SKIP_FETCHCONTENT})
		list(APPEND VARIABLES_TO_BE_CLEARED "MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FETCHCONTENT")
	endif()


	# Remove REQUIRED keyword so we have a chance at trying different methods to satisfy the
	# dependency without CMake erroring in between.
	set(FIND_ARGS "${ARGN}")
	list(APPEND VARIABLES_TO_BE_CLEARED "FIND_ARGS")
	list(FIND FIND_ARGS "REQUIRED" REQUIRED_IDX)
	list(APPEND VARIABLES_TO_BE_CLEARED "REQUIRED_IDX")
	if ("${REQUIRED_IDX}" GREATER_EQUAL 0)
		set(DEP_REQUIRED ON)
		list(REMOVE_AT FIND_ARGS "${REQUIRED_IDX}")
	else()
		set(DEP_REQUIRED OFF)
	endif()
	list(APPEND VARIABLES_TO_BE_CLEARED "DEP_REQUIRED")
	# We also want a custom handling of the QUIET option
	list(FIND FIND_ARGS "QUIET" QUIET_IDX)
	list(APPEND VARIABLES_TO_BE_CLEARED "QUIET_IDX")
	if ("${QUIET_IDX}" GREATER_EQUAL 0)
		set(DEP_QUIET ON)
		list(REMOVE_AT FIND_ARGS "${QUIET_IDX}")
	else()
		set(DEP_QUIET OFF)
	endif()
	list(APPEND VARIABLES_TO_BE_CLEARED "DEP_QUIET")

	if (NOT MUMBLE_DEP_DEBUG_MODE)
		set(QUIET_KEYWORD "QUIET")
		list(APPEND VARIABLES_TO_BE_CLEARED "QUIET_KEYWORD")
	endif()

	if (NOT MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FIND_PACKAGE)
		if (DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_FIND_PACKAGE_ARGS)
			set(FIND_PACKAGE_ARGS "${MUMBLE_DEP_${DEP_NAME_UPPER}_FIND_PACKAGE_ARGS}")
		else()
			set(FIND_PACKAGE_ARGS "${FIND_ARGS}")
		endif()

		if (DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_FIND_PACKAGE_EXTRA_ARGS)
			set(FIND_PACKAGE_ARGS "${FIND_PACKAGE_ARGS};${MUMBLE_DEP_${DEP_NAME_UPPER}_FIND_PACKAGE_EXTRA_ARGS}")
		endif()
		list(APPEND VARIABLES_TO_BE_CLEARED "FIND_PACKAGE_ARGS")

		find_package(${DEP_NAME} ${FIND_PACKAGE_ARGS} ${QUIET_KEYWORD} BYPASS_PROVIDER)
	endif()

	
	if (NOT ${DEP_NAME}_FOUND AND NOT MUMBLE_DEP_${DEP_NAME_UPPER}_SKIP_FETCHCONTENT AND DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_FETCHCONTENT_ID)
		FetchContent_MakeAvailable(${MUMBLE_DEP_${DEP_NAME_UPPER}_FETCHCONTENT_ID})
		set(${DEP_NAME}_FOUND TRUE)
		set(${DEP_NAME}_FETCHED TRUE)
	endif()


	if (DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_EXPECTED_MAIN_TARGET)
		if (NOT TARGET ${MUMBLE_DEP_${DEP_NAME_UPPER}_EXPECTED_MAIN_TARGET})
			set(${DEP_NAME}_FOUND FALSE)
		endif()
	endif()

	if (${DEP_NAME}_FOUND AND NOT DEFINED MUMBLE_DEP_${DEP_NAME_UPPER}_LICENSE AND NOT DEP_NAME_UPPER STREQUAL "THREADS" AND NOT DEP_NAME_UPPER STREQUAL "PKGCONFIG")
		message(WARNING "Using dependency '${DEP_NAME}' with unknown license (${DEP_NAME_UPPER})")
	endif()
	

	if (${DEP_NAME}_VERSION)
		set(VERSION_ARGS "HANDLE_VERSION_RANGE;VERSION_VAR;${DEP_NAME}_VERSION")
		list(APPEND VARIABLES_TO_BE_CLEARED "VERSION_ARGS")
	endif()

	find_package_handle_standard_args("${DEP_NAME}"
		REQUIRED_VARS "${DEP_NAME}_FOUND"
		NAME_MISMATCHED
		${VERSION_ARGS}
	)


	# Clear up created variables
	list(REVERSE VARIABLES_TO_BE_CLEARED)
	foreach(CURRENT IN LISTS VARIABLES_TO_BE_CLEARED)
		unset("${CURRENT}")
	endforeach()
	unset(CURRENT)
endmacro()

cmake_language(SET_DEPENDENCY_PROVIDER mumble_provide_dependency SUPPORTED_METHODS FIND_PACKAGE)
