.TH mumble\-server\-user\-wrapper 1 "2015 December 27"
.SH NAME
mumble\-server\-user\-wrapper \- User wrapper for mumble\-server.
.SH SYNOPSIS
.B mumble\-server\-user\-wrapper
.RI [ options ]
.SH DESCRIPTION
mumble\-server is the server component of Mumble, a low\-latency, high quality VoIP
application. mumble\-server\-wrapper is a wrapper script to make it easier for normal
users to set up their own, private Mumble server.
.SH OPTIONS
.TP
.BI \-d \ "directory"
Set directory to use. By default, the wrapper script uses $HOME/murmur
.TP
.B \-s
Check if mumble\-server process is running.
.TP
.B \-k
Terminate running mumble\-server process.
.TP
.B \-i
Initialize only, do not start the server.
.TP
.BI \-p \ "password"
Specify password for the SuperUser account and exit. SuperUser is the
mumble equivalent of root, a special user which bypasses all access
restrictions.
.SH NOTES
To create your own private server, you first want to run
.IP
mumble\-server\-user\-wrapper \-i
.LP
Then edit ~/murmur/murmur.ini to set the various configuration settings. The
most important is probably the port; unless you're the only mumble\-server process
running on this server, you'll need to change it.

When you're happy with your settings, you need to set the password for
SuperUser, which is your administrator account.
.IP
mumble\-server\-user\-wrapper \-p 
.I "<password>"
.LP

Once this is done, simply run
.IP
mumble\-server\-user\-wrapper
.LP
to start the server.
.SH SEE ALSO
.BR mumble\-server (1).
.br
.SH AUTHORS
mumble and mumble\-server were written by The Mumble Developers.
