.TH mumble\-server 1 "2016 May 9"
.SH NAME
mumble\-server - VoIP server.
.SH SYNOPSIS
.B mumble\-server
[\fB-ini \fIinifile\fR] [\fB-fg\fR] [\fB-v\fR]
.br
.B mumble\-server \-supw\fR \fIpassword\fR [\fIserverid\fR]
.br
.B mumble\-server \-readsupw\fR [\fIserverid\fR]
.br
.B mumble\-server \-disablesu\fR [\fIserverid\fR]
.br
.B mumble\-server \-limits
.br
.B mumble\-server \-wipessl
.br
.B mumble\-server \-wipelogs
.br
.B mumble\-server \-loggroups
.br
.B mumble\-server \-logacls
.br
.B mumble\-server \-license
.br
.B mumble\-server \-authors
.br
.B mumble\-server \-third\-party\-licenses
.br
.B mumble\-server \-version\fR|\fB\-\-version
.br
.B mumble\-server \-h\fR|\fB\-help\fR|\fB\-\-help
.SH DESCRIPTION
mumble\-server is the server component of Mumble, a low-latency, high quality VoIP
application.
.SH OPTIONS
.TP
.B \-h, \-help, \-\-help
Show a summary of the options.
.TP
.B \-ini \fIinifile
Specify which ini file to use. Without this option, mumble\-server will search for
a murmur.ini file and will fall back to builtin defaults if one isn't found.
.TP
.B \-fg
Run in the foreground (do not fork).
.TP
.B \-v
Verbose mode, slightly more information is logged.
.TP
.B \-supw \fIpassword\fR [\fIserverid\fR]
This sets the SuperUser password for a server. SuperUser is a special account
(similar to root) which bypasses all access controls. This command may be used
while the server is running. Optionally takes a \fIserverid\fR representing the
virtual server to set the password for.
.TP
.B \-readsupw\fR\ [\fIserverid\fR]
Reads SuperUser password from stdin. Optionally takes a \fIserverid\fR
representing the virtual server to set the password for.
.TP
.B \-disablesu\fR\ [\fIserverid\fR]
Disables the SuperUser account. Optionally takes a \fIserverid\fR representing
the virtual server to disable the SuperUser account on.

Disabling the SuperUser account makes it impossible to log in as SuperUser
until a new password is set. You can set a new SuperUser password with the
\-supw parameter.
.TP
.B \-limits
Tests and shows how many file descriptors and threads can be created. The
purpose of this option is to test how many clients the server can handle. The
server will exit after this test.
.TP
.B \-wipessl
Remove SSL certificates from database.
.TP
.B \-wipelogs
Remove all log entries from database.
.TP
.B \-loggroups
Turns on logging for group changes for all servers.
.TP
.B \-logacls
Turns on logging for ACL changes for all servers.
.TP
.B \-license
Show mumble\-server's license.
.TP
.B \-authors
Show mumble\-server's authors.
.TP
.B \-third\-party\-licenses
Show licenses for third-party software used by mumble\-server.
.TP
.B \-version, \-\-version
Show version information.
.SH SIGNALS
.TP
.BR SIGHUP
Perform a log rotation.
This causes mumble\-server to re-open its log file.
.TP
.BR SIGUSR1
Gracefully reload the TLS settings specified in murmur.ini without interrupting service.

When this signal is received, the server will apply the new TLS settings (certificate,
private key, and Diffie-Hellman parameters) to all virtual servers that use the TLS settings
from murmur.ini.

Virtual servers that have overridden the settings from murmur.ini will not
be affected by this signal. Those servers can be updated using the updateCertificate RPC call.
.SH SEE ALSO
.BR mumble (1),
.BR murmur\-user\-wrapper (1).
.br
.SH AUTHORS
mumble and mumble\-server were written by The Mumble Developers.
