
// Auto-generated by scripts/mkwrapper.pl . Do not edit manually.

static void impl_Server_startListening(const ::Murmur::AMD_Server_startListeningPtr cb, int server_id,  ::Ice::Int p1,  ::Ice::Int p2) {}
static void impl_Server_stopListening(const ::Murmur::AMD_Server_stopListeningPtr cb, int server_id,  ::Ice::Int p1,  ::Ice::Int p2) {}
