name: Build and Sign Windows Executable

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  CMAKE_OPTIONS: -Dtests=OFF -Dsymbols=ON -Ddisplay-install-paths=ON -Dtest-lto=OFF

jobs:

  fetch_build_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.fetch.outputs.build_number }}
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - id: fetch
        shell: bash
        run: |
          build_version="$("${{ github.workspace }}/scripts/mumble-version.py")"
          build_number="$("${{ github.workspace }}/scripts/mumble-build-number.py" \
            --commit "${{ github.sha }}" --version "${build_version}" \
            --password "${{ secrets.BUILD_NUMBER_TOKEN }}" --default 0)"
          echo "build_number=${build_number}" >> "$GITHUB_OUTPUT"

  build:
    needs: [ fetch_build_number ]

    strategy:
        fail-fast: false
        matrix:
            os: [windows-2022]
            type: [static]
            arch: [x86_64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: 'recursive'
          fetch-depth: 1

    - name: Set environment variables
      run: $GITHUB_WORKSPACE/.github/workflows/set_environment_variables.sh "${{ matrix.os }}" "${{ matrix.type }}" "${{ matrix.arch }}" "${{ github.workspace }}"
      shell: bash

    - uses: actions/cache@v4
      with:
          path: '${{ env.MUMBLE_ENVIRONMENT_DIR }}'
          key: ${{ env.MUMBLE_ENVIRONMENT_VERSION }}

    - uses: ./.github/actions/install-dependencies
      with:
          type: ${{ matrix.type }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

    - name: Build
      run: ./.github/workflows/build.sh "${{ matrix.os }}" "${{ matrix.type }}" "${{ matrix.arch }}"
      shell: bash
      env:
          MUMBLE_BUILD_NUMBER: ${{ needs.fetch_build_number.outputs.build_number }}

    - uses: ./.github/actions/sign-binaries
      with:
          signpath-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          build-number: ${{ needs.fetch_build_number.outputs.build_number }}
          type: ${{ matrix.type }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
